import PDFDocument from "pdfkit";
import { kcseGrade, meanGrade } from "@/lib/grading";

export interface ReportCardSubjectRow {
  subject: string;
  score: number;
  maxScore: number;
}

export interface ReportCardParams {
  schoolName: string;
  schoolTagline: string | null;
  studentName: string;
  admissionNumber: string | null;
  className: string | null;
  guardianName: string | null;
  term: string;
  rows: ReportCardSubjectRow[];
  attendanceRate: number | null; // 0-100, or null if no attendance recorded
}

const PAGE_MARGIN = 50;
const COLS = {
  subject: PAGE_MARGIN,
  score: 300,
  max: 360,
  pct: 420,
  grade: 480,
};

/** Builds a one-page PDF report card and resolves with the finished buffer. */
export function buildReportCardPdf(params: ReportCardParams): Promise<Buffer> {
  const { schoolName, schoolTagline, studentName, admissionNumber, className, guardianName, term, rows, attendanceRate } = params;

  const doc = new PDFDocument({ size: "A4", margin: PAGE_MARGIN });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(chunk));
  const done = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))));

  // ---- Header ----
  doc.font("Helvetica-Bold").fontSize(20).text(schoolName, { align: "center" });
  if (schoolTagline) {
    doc.font("Helvetica-Oblique").fontSize(10).fillColor("#555555").text(schoolTagline, { align: "center" });
    doc.fillColor("#000000");
  }
  doc.moveDown(0.5);
  doc.font("Helvetica-Bold").fontSize(14).text("Student Report Card", { align: "center" });
  doc.font("Helvetica").fontSize(11).text(term, { align: "center" });
  doc.moveDown(1);

  const lineY = doc.y;
  doc.moveTo(PAGE_MARGIN, lineY).lineTo(545, lineY).strokeColor("#cccccc").stroke();
  doc.moveDown(1);

  // ---- Student info ----
  doc.font("Helvetica-Bold").fontSize(11);
  const infoStartY = doc.y;
  doc.text("Student:", PAGE_MARGIN, infoStartY, { continued: true }).font("Helvetica").text(` ${studentName}`);
  doc.font("Helvetica-Bold").text("Admission #:", PAGE_MARGIN, doc.y + 4, { continued: true }).font("Helvetica").text(` ${admissionNumber ?? "—"}`);
  doc.font("Helvetica-Bold").text("Class:", PAGE_MARGIN, doc.y + 4, { continued: true }).font("Helvetica").text(` ${className ?? "—"}`);
  doc.font("Helvetica-Bold").text("Guardian:", PAGE_MARGIN, doc.y + 4, { continued: true }).font("Helvetica").text(` ${guardianName ?? "—"}`);
  doc.moveDown(1.2);

  // ---- Subjects table ----
  const tableTop = doc.y;
  doc.font("Helvetica-Bold").fontSize(10).fillColor("#000000");
  doc.text("Subject", COLS.subject, tableTop);
  doc.text("Score", COLS.score, tableTop);
  doc.text("Max", COLS.max, tableTop);
  doc.text("%", COLS.pct, tableTop);
  doc.text("Grade", COLS.grade, tableTop);

  doc.moveTo(PAGE_MARGIN, tableTop + 15).lineTo(545, tableTop + 15).strokeColor("#000000").stroke();

  let rowY = tableTop + 22;
  doc.font("Helvetica").fontSize(10);

  const pointsList: number[] = [];
  for (const row of rows) {
    const pct = row.maxScore > 0 ? (row.score / row.maxScore) * 100 : 0;
    const { letter, points } = kcseGrade(pct);
    pointsList.push(points);

    doc.text(row.subject, COLS.subject, rowY, { width: COLS.score - COLS.subject - 10 });
    doc.text(String(row.score), COLS.score, rowY);
    doc.text(String(row.maxScore), COLS.max, rowY);
    doc.text(`${Math.round(pct)}%`, COLS.pct, rowY);
    doc.text(letter, COLS.grade, rowY);
    rowY += 20;

    if (rowY > 720) {
      doc.addPage();
      rowY = PAGE_MARGIN;
    }
  }

  doc.moveTo(PAGE_MARGIN, rowY).lineTo(545, rowY).strokeColor("#cccccc").stroke();
  rowY += 15;

  // ---- Summary ----
  const overall = meanGrade(pointsList);
  doc.font("Helvetica-Bold").fontSize(11);
  if (overall) {
    doc.text(`Mean grade: ${overall.letter} (${overall.points} points)`, PAGE_MARGIN, rowY);
    rowY = doc.y + 6;
  } else {
    doc.font("Helvetica").fontSize(10).fillColor("#666666").text("No grades recorded for this term yet.", PAGE_MARGIN, rowY);
    doc.fillColor("#000000");
    rowY = doc.y + 6;
  }

  if (attendanceRate !== null) {
    doc.font("Helvetica").fontSize(10).text(`Attendance: ${attendanceRate}% present`, PAGE_MARGIN, rowY);
    rowY = doc.y + 6;
  }

  // ---- Signature lines ----
  rowY = Math.max(rowY + 60, 700);
  doc.font("Helvetica").fontSize(10);
  doc.moveTo(PAGE_MARGIN, rowY).lineTo(220, rowY).strokeColor("#000000").stroke();
  doc.text("Class Teacher", PAGE_MARGIN, rowY + 4);
  doc.moveTo(340, rowY).lineTo(510, rowY).stroke();
  doc.text("Principal", 340, rowY + 4);

  doc.font("Helvetica").fontSize(8).fillColor("#999999").text(`Generated by Aclass on ${new Date().toLocaleDateString("en-KE")}`, PAGE_MARGIN, 780, { align: "center", width: 495 });

  doc.end();
  return done;
}
